better error code

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -62,14 +62,17 @@ runs:
           #!/bin/bash
           set +e
 
+            echo "github ref is ${GITHUB_REF}"
+
             if [ -n "${INPUT_TARGET_ENV}" ]; then
               TARGET_ENV="${INPUT_TARGET_ENV}"
             elif [ -n "${PR_NUM}" ]; then
               TARGET_ENV="pr-${PR_NUM}"
-            else
-              echo "todo, check that we're on a main/master/default branch"
-              echo "todo, exit with error code if we're on something unaccounted"
+            elif [ "${GITHUB_REF}" == "refs/heads/main" ] || [ "${GITHUB_REF}" == "refs/heads/master" ]; then
               TARGET_ENV='dev'
+            else
+              echo "Error: you must set the 'target_env' parameter when running this action on a branch that is not 'main' or 'master' or when not executing a workflow in a pull request."
+              exit 1
             fi
 
           echo "PANTHEON_TARGET_ENV=${TARGET_ENV}" >> $GITHUB_ENV
